# Generated by Django 5.2.10 on 2026-02-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('sbd', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('toan', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ngu_van', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ngoai_ngu', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vat_li', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hoa_hoc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sinh_hoc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lich_su', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dia_li', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gdcd', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ma_ngoai_ngu', models.CharField(max_length=2)),
            ],
        ),
    ]
